//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cells
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Depth { get; set; }
        public Nullable<int> SizeControl { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> AmountControl { get; set; }
        public Nullable<int> Stillage { get; set; }
        public Nullable<int> Tier { get; set; }
        public Nullable<int> Position { get; set; }
        public int TypeID { get; set; }
        public int WarehouseID { get; set; }
        public int RegionID { get; set; }
    
        public virtual CellTypes CellTypes { get; set; }
        public virtual Regions Regions { get; set; }
        public virtual Warehouses Warehouses { get; set; }
    }
}
